server.port=${PORT:8080}
spring.application.name=kandamma-kids-wear
spring.cloud.gcp.project-id=qwiklabs-gcp-02-eb01df7117c0
spring.cloud.gcp.firestore.project-id=qwiklabs-gcp-02-eb01df7117c0

# Agent Engine Integration
kandamma.agent.engine-url=https://us-east1-aiplatform.googleapis.com/v1/projects/363499579686/locations/us-east1/reasoningEngines/6312082949806227456:query
kandamma.media.bucket-url=https://storage.googleapis.com/qwiklabs-gcp-02-eb01df7117c0-kandamma-media/
kandamma.whatsapp.admin-phone=919876543210
